### ISSUE TITLE
Use app to imput data from ESPEasy connected P1 Meter

### ISSUE THREAD

**Issue by HerrieMan72** [gruijter/com.gruijter.youless#1]
Hi Robin,
i'm currently using a simple Wemos board running EspEasy code to connect my P1-meter to my Domoticz server. The connection is done via the P1 gateway plugin in espeasy (source: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P044_P1WifiGateway.ino), which seems to use a simple ser2net setup with a little added frame-checking.
Would it be possible to use this setup with one of your P1 apps on Homey so I can also get my P1 data to my Homey (would eventually prefer that over my current Domoticz setup).

**Comment by gruijter** [comment]
No, this wouldnt work. The information is not in a format that one of my apps can work with. A new app would be needed for that. You can build your own app 😉

**Comment by HerrieMan72** [comment]
Hmm, that's to bad, I was hoping these youless devices would also just pass the P1 telegram from the meter, but apparently that isn't the case.
I'm no software developer, so writing my own app is a bit beyond my possibilities, i'll check if some other options are available to get my energy data into my Homey.
