### ISSUE TITLE
Request path contains unescaped characters

### ISSUE THREAD

**Issue by nielsvn92** [gruijter/com.gruijter.youless#2]
I have the Youless LS120 with firmware version 1.4.1-PO (PVOutput).
After I've flashed the PVOutput firmware, the following error appeared:
`[ManagerDrivers] [LS120] [0] poll error: Error: Invalid content-type. Expected application/json but received text/plain`. I use the P1 version without S0 measurements.

I tried to add the device again in Homey, but I got the same error.

If you need more information, please tell me.

**Comment by gruijter** [comment]
If you want to use the Homey app, you have to flash the EL firmware. It does not work with PO.
